baseURL = "https://blog.medgelabs.io/"
title = "Medgelabs"
languageCode = "en"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
#disqusShortname = "XXX"

[author]
name = "Matthew Edge"
github = "MatthewEdge"
linkedin = "matthewedge"
stackoverflow = "1735905/mattedge"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4

  [goldmark.renderer]
    unsafe = true  # enable raw HTML in Markdown
